import sql from 'k6/x/sql';

// The second argument is an Oracle connection string, e.g.
// oracle://myuser:mypass@127.0.0.1:5432/db
const db = sql.open('oracle', '');

export function setup() {
    db.exec(`CREATE TABLE keyvalues (
    id number GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1),
    key varchar(50),
    value varchar(50)
  )`);
}

export function teardown() {
    db.close();
}

export default function () {
    db.exec("INSERT INTO keyvalues VALUES (DEFAULT, 'plugin-name', 'k6-plugin-sql')");
    let results = sql.query(db, "SELECT * FROM keyvalues WHERE key = :1",'plugin-name');
    for (const row of results) {
        console.log(`key: ${row.KEY}, value: ${row.VALUE}`);
    }
}
