name: CI
on:
  # Enable manually triggering this workflow via the API or web UI
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    tags:
      - v*
  pull_request:

permissions:
  contents: read

jobs:
  checks:
    uses: grafana/k6-ci/.github/workflows/all.yml@03469f9ae7aad25369827832c456e8f8b7b8c1c2 # v0.5.0
    with:
      k6-ci-ref: 03469f9ae7aad25369827832c456e8f8b7b8c1c2 # v0.5.0
